package org.lasalle.scoreboard;

import org.junit.Before;

/**
 * Test skeleton to share action and final values
 * 
 * @author lasalle
 */
public abstract class ScoreBoardTest {

	/**
	 * A_TEAM: test football team
	 */
	protected static final String A_TEAM = "A_TEAM";
	/**
	 * B_TEAM: test football team
	 */
	protected static final String B_TEAM = "B_TEAM";
	/**
	 * C_TEAM: test football team
	 */
	protected static final String C_TEAM = "C_TEAM";
	/**
	 * D_TEAM: test football team
	 */
	protected static final String D_TEAM = "D_TEAM";
	/**
	 * E_TEAM: test football team
	 */
	protected static final String E_TEAM = "E_TEAM";
	/**
	 * F_TEAM: test football team
	 */
	protected static final String F_TEAM = "F_TEAM";

	/**
	 * Default scores associated to new game
	 */
	protected static final int DEFAULT_SCORE = 0;

	/**
	 * The tested ScoreBoard
	 */
	protected ScoreBoard _scoreBoard = null;

	/**
	 * Initialization of the ScoreBoard
	 * 
	 * @throws Exception
	 */
	@Before
	public void setUp() throws Exception {
		_scoreBoard = new ScoreBoard();
	}
	
	/**
	 * Generate a single summary line as it has to be generated by the ScoreBoard
	 * 
	 * @param num  line number
	 * @param game concerned game
	 * @return the excepted summary line
	 */
	protected String genSummaryLine(int num, Game game) {
		return String.format("%s. %s %s - %s %s\n", num, game.getHomeTeamName(), game.getHomeTeamScore(),
				game.getAwayTeamName(), game.getAwayTeamScore());
	}
}
